use std::path::PathBuf;

use clap::Args;

use lingmo_core_engine::error::BuildResult;
use lingmo_core_engine::{logging, BuildError};

#[derive(Args, Debug)]
pub struct InitArgs {
    /// Output path for the generated config
    #[arg(short, long, default_value = "lingmo.toml")]
    pub output: PathBuf,

    /// Profile to pre-fill (desktop, server, core)
    #[arg(short, long, default_value = "desktop")]
    pub profile: String,

    /// Desktop environment (kde, gnome, xfce, etc.)
    #[arg(short, long)]
    pub desktop: Option<String>,

    /// Force overwrite existing file
    #[arg(short, long)]
    pub force: bool,

    /// Verbose output
    #[arg(short, long, action = clap::ArgAction::Count)]
    pub verbose: u8,
}

pub fn execute(args: &InitArgs) -> BuildResult<()> {
    logging::init_logging(args.verbose, false);

    if args.output.exists() && !args.force {
        return Err(BuildError::Config(format!(
            "Config file already exists: {}. Use --force to overwrite",
            args.output.display()
        )));
    }

    let desktop_line = match &args.desktop {
        Some(de) => format!("desktop = \"{}\"", de),
        None => "# desktop = \"kde\"".to_string(),
    };

    let template = format!(
        r##"# Lingmo Builder Configuration
# Generated by `lingmo-builder init`

[distro]
name = "LingmoOS"
version = "1.0"
codename = "trixie"
mirror = "https://mirrors.tuna.tsinghua.edu.cn/debian"
architecture = "amd64"
components = ["main", "contrib", "non-free", "non-free-firmware"]

profile = "{}"
{}

[installer]
type = "calamares"
# For Debian Installer:
# type = "debian-installer"
# mode = "graphical"   # graphical, text, or ncurses

[repositories]
default_format = "deb822"

[repositories.debian]
mirror = "https://mirrors.tuna.tsinghua.edu.cn/debian"
security_mirror = "https://mirrors.tuna.tsinghua.edu.cn/debian-security"
suite = "trixie"
components = ["main", "contrib", "non-free", "non-free-firmware"]
source_enabled = false

[[repositories.extra]]
name = "lingmo"
repo_type = "obs"
url = "http://download.opensuse.org/repositories/home:/LingmoOS/Debian_13/"
suite = "/"
key_url = "https://download.opensuse.org/repositories/home:LingmoOS/Debian_13/Release.key"
key_path = "/etc/apt/keyrings/lingmo.gpg"
enabled = true

[packages]
additional = []
remove = []

[packages.pin_priorities]

[system]
hostname = "lingmo"
locale = "en_US.UTF-8"
timezone = "UTC"
keyboard_layout = "us"
kernel_cmdline = "quiet splash"

[[system.users]]
username = "live"
password_hash = "$y$j9T$..."  # Use mkpasswd -m yescrypt
shell = "/bin/bash"
groups = ["sudo", "audio", "video", "cdrom", "plugdev"]
sudo = true

[output]
iso_name = "lingmo.iso"
iso_label = "LINGMO_LIVE"
iso_volume = "LINGMO_LIVE"
output_dir = "./output"
work_dir = "./work"
squashfs_compression = "zstd"
squashfs_block_size = 131072

[volume]
# Splitting strategy: "single" (default), "size", "plugin", "profile"
strategy = "single"
# Max bytes per volume when strategy = "size" (default: 1 GiB)
max_volume_size = 1073741824
# SquashFS compression
compression = "zstd"
# Block size in bytes (128 KiB default)
block_size = 131072
# Output filename pattern
output_pattern = "filesystem.part{{}}.squashfs"
# Generate manifest JSON
generate_manifest = true
# Verify checksums after build
verify_checksums = true

[cache]
enabled = false
directory = "./cache"
stages = ["bootstrap", "install-base"]

# Plugin selection
plugins = [
    "core",
    # "kde",
    # "gnome",
    # "xfce",
    # "networkmanager",
    # "nvidia",
]

# Custom hooks (optional)
# [[hooks]]
# name = "my-custom-setup"
# script = """
# echo "Running custom setup..."
# apt-get install -y my-package
# """
# stage = "chroot-hooks"
# chroot = true
# order = 50
"##,
        args.profile, desktop_line
    );

    if let Some(parent) = args.output.parent() {
        std::fs::create_dir_all(parent).map_err(|e| BuildError::Io {
            path: parent.to_path_buf(),
            source: e,
        })?;
    }

    std::fs::write(&args.output, &template).map_err(|e| BuildError::Io {
        path: args.output.clone(),
        source: e,
    })?;

    tracing::info!("Configuration template written to {}", args.output.display());
    Ok(())
}
